---
book_repo: pivotal-cf/docs-book-antivirus
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-addon-antivirus
    ref: 'master'
  directory: addon-antivirus
  subnav_template: addon_antivirus.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: ClamAV Add-on for PCF
    search_placeholder: ClamAV Add-on for PCF
    url_prefix: addon-antivirus/1-3
    local_product_version: "1.3"
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/addon-antivirus/1-2
        display_name: v1.2
